### ISSUE TITLE
Blank page when uBlock Origin is enabled.

### ISSUE THREAD

**Issue by ymcatar** [leoyuholo/aimole#15]
Here is the console output in Chrome:

![screen shot 2016-03-21 at 22 44 21](https://cloud.githubusercontent.com/assets/2025246/13922268/7a53829a-efb6-11e5-9d07-c0f2b32bf0dc.png)

**Comment by leoyuholo** [comment]
related for angulartics
https://github.com/angulartics/angulartics/issues/58

**Comment by leoyuholo** [comment]
should be solved by commit https://github.com/leoyuholo/aimole/commit/20ad9f0344e7dbf4e77c63bb86db5d038d32bfa1

**Comment by ymcatar** [comment]
Working now.
